apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: influxdb
type: Opaque
data:
  # Password: 9hN+MwyhBQF3oSNrAOkJr+0Id4TJfb8+Lv9pd/Ly0A4=
  admin-password: OWhOK013eWhCUUYzb1NOckFPa0pyKzBJZDRUSmZiOCtMdjlwZC9MeTBBND0=
  admin-token: ""