[karmada-host]
vps9 ansible_host=46.250.232.0 ansible_user=root ansible_ssh_pass=MeBqFkwC6ChohF37dEMd

[clusters]
vn2 kubeconfig=config-vn2 context=vn2
jp kubeconfig=config-jp context=jp
; sg kubeconfig=config-sg context=sg
eu kubeconfig=config-eu context=eu
us kubeconfig=config-us context=us
