apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-eu
  namespace: elasticsearch
  labels:
    cluster: eu
    environment: production
spec:
  version: 8.17.0
  count: 1

  elasticsearchRef:
    name: elasticsearch-eu

  podTemplate:
    metadata:
      labels:
        app: kibana
        cluster: eu
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi

  http:
    tls:
      selfSignedCertificate:
        disabled: true
