apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: murror-api-fix-dynamic-ins
  namespace: fix-dynamic-ins
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: murror-api
  endpoints:
  - port: http
    path: /api/metrics
    interval: 30s
    scrapeTimeout: 10s
