---
k3s_version: v1.22.3+k3s1
ansible_user: root
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--no-deploy traefik --write-kubeconfig-mode 644"
extra_agent_args: ""
