# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dev-access
  labels:
    name: dev-access
    app: dev-access
    environment: dev
    owner: dev-team
    purpose: access-logs
    created-by: dev-team
    created-at: 2023-10-01
    managed-by: dev-team
    version: v1
    app.kubernetes.io/instance: dev-access
    app.kubernetes.io/managed-by: dev-team
    app.kubernetes.io/created-by: dev-team
---
# Create service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-logger
  namespace: dev-access
  labels:
    name: dev-logger
    app: dev-logger
    environment: dev
    owner: dev-team
    purpose: access-logs
    created-by: dev-team
    created-at: 2023-10-01
    managed-by: dev-team
    version: v1
    app.kubernetes.io/instance: dev-logger
    app.kubernetes.io/managed-by: dev-team
    app.kubernetes.io/created-by: dev-team
secrets:
  - name: dev-logger-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-logger-secret
  namespace: dev-access
  annotations:
    kubernetes.io/service-account.name: dev-logger
type: kubernetes.io/service-account-token
