apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: influxdb
type: Opaque
data:
  # Password: jNIyhJyGalpURDPdiDik+LLuv5xMIP/Cr9WQs1jT4UQ=
  admin-password: ak5JeWhKeUdhbHBVUkRQZGlEaWsrTEx1djV4TUlQL0NyOVdRczFqVDRVUT0=
  admin-token: ""
