apiVersion: v1
kind: Secret
metadata:
  name: streaming-replica-pgvector-secret
  namespace: postgres-db
  labels:
    cnpg.io/cluster: postgresql-pgvector
    app: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: streaming_replica
  password: jQ35rsPn9vrYKDOXqzkW0zqkWvB65D7XztBQXY9BTCo=