apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
stringData:
  MINIO_ROOT_USER: minio-admin
  MINIO_ROOT_PASSWORD: minio-admin-password-change-me
  MINIO_ACCESS_KEY: postgres-wal-access-key
  MINIO_SECRET_KEY: postgres-wal-secret-key-change-me